name: reminder
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 0.1.2
  google_fonts: 0.1.1
  table_calendar: 2.2.1
  intl: 0.16.0
  line_icons: 0.2.0
  sqflite: 1.1.5
  path_provider: 1.4.0
  flutter_cupertino_date_picker: 1.0.12
  simple_gesture_detector: 0.1.4
  flutter_datetime_picker: 1.3.1
  datetime_picker_formfield: 1.0.0
  sliding_up_panel: 1.0.0
  rxdart: 0.23.1
  flutter_slidable: 0.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
